import {
  SERVER_ENDPOINT,
  UPLOAD_PRESET,
  CLOUD_NAME,
  CLOUNDINARY_API_BASE_URL,
  LOCAL_ENDPOINT
} from "@env";

export default {
  SERVER_ENDPOINT,
  UPLOAD_PRESET,
  CLOUD_NAME,
  CLOUNDINARY_API_BASE_URL,
  LOCAL_ENDPOINT
};
